server:
	g++ -std=c++11 charvar.cpp numericvar.cpp parse.cpp realvar.cpp stringvar.cpp var.cpp wrap.cpp Connection.cpp TCPServerSocket.cpp TCPSocket.cpp  GarbageCollector.cpp Thread.cpp server.cpp -lpthread -o server && ./server

client:
	g++ client.cpp -o client && ./client